config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'welcome/index'
  
  authenticated :user do
    root 'notes#index', as: 'authenticated_root'
  end
  
  root 'welcome#index'
  
  resources :notes
  
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]
  
  def index
    @notes = Note.where(user_id: current_user)
  end
  
  def show
  end
  
  def new
    @note = current_user.notes.build
  end
  
  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end
  
  def destroy
    @note.destroy
    redirect_to notes_path
  end
  
  
  private
  
    def find_note
      @note = Note.find(params[:id])
    end
    
    def note_params
      params.require(:note).permit(:title, :content)
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notepad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"></link>
  <%= csrf_meta_tags %>
</head>
<body>
  
<header>
  <div class="header_inner">
    <%= link_to "NOTEPAD", root_path, class: "brand-name" %>
    <nav>
      <% if user_signed_in? %>
        <%= link_to "Add Note", new_note_path %>
        <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Register", new_user_registration_path %>
        <%= link_to "Log In", new_user_session_path %>
      <% end %>
    </nav>
  </div>
</header>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= simple_form_for(@note) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.button :submit, class: "button" %>
<% end %>  

app/views/notes/edit.html.erb
<div class="wrapper_with_padding">
  <h1>Edit Note</h1>
  <%= render 'form' %>
  <%= link_to "Cancel", @note %>
</div>

app/views/notes/index.html.erb
<div class="wrapper_with_padding">
  <div class="clearfix" id="notes">
    <% unless @notes.blank? %>
      <% @notes.each do |note| %>
        <a href="<%= (url_for [note]) %>">
          <div class="note">
            <p class="title">
              <%= note.title %>
            </p>
            <p class="date">
              Created <%= time_ago_in_words(note.created_at) %> ago
            </p>
          </div>
        </a>
      <% end %>
    <% else %>
      <h2>Add a Note</h2>
      <p>You haven't created any notes yet.</p>
      <button>
        <%= link_to "Add Note", new_note_path %>
      </button>
    <% end %>
  </div>
</div>

app/views/notes/new.html.erb
<div class="wrapper_with_padding">
  <h1>Add Note</h1>
  <%= render 'form' %>
</div>

app/views/notes/show.html.erb
<div class="wrapper_with_padding">
  <div id="note_show">
    <h1 class="title">
      <%= @note.title %>
    </h1>
    <p><%= simple_format(@note.content) %></p>
    <div class="buttons">
      <%= link_to "Edit", edit_note_path(@note), class: "button" %>
      <%= link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are you sure?" }, class: "button" %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div id="banner">
  <div class="banner_content">
    <h1>Notepad</h1>
    <p>Your online notebook. Never forget an idea again.</p>
    <button>
      <%= link_to "Sign Up", new_user_registration_path %>
    </button>
  </div>
</div>
<div id="testimonial">
  <div class="wrapper">
    <p class="quote">"The greatest notebook application. Period."</p>
    <p class="name">- John Lander</p>
  </div>
</div>
<div id="callouts">
  <div class="callout_inner">
    <div class="wrapper">
      <div class="callout">
        <i class="fa fa-pencil"></i>
        <h2>Notes</h2>
        <p>Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.</p>
      </div>
      <div class="callout">
        <i class="fa fa-rocket"></i>
        <h2>Notes</h2>
        <p>Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.</p>
      </div>
      <div class="callout">
        <i class="fa fa-bolt"></i>
        <h2>Notes</h2>
        <p>Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.</p>
      </div>
    </div>
  </div>
</div>
<div id="bottom_cta">
  <div class="wrapper">
    <h2>For Realz!</h2>
    <p>I want you to sign up.</p>
    <button>
      <%= link_to "Click Meee!!!", new_user_registration_path %>
    </button>
  </div>
</div>
<footer>
  <p>&copy; John Lander</p>
</footer>